version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_m2
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local